
//保存用户数据信息
const HM_1_P:string = 'https://api-harmony-teach.itheima.net/hm/userInfo'
//获取用户数据
const HM_2_G:string = 'https://api-harmony-teach.itheima.net/hm/userInfo'
//修改用户头像
const HM_3_P:string = 'https://api-harmony-teach.itheima.net/hm/userInfo/avatar'
//完善用户头像和昵称
const HM_4_P:string = 'https://api-harmony-teach.itheima.net/hm/userInfo/profile'
//查询个人学习数据
const HM_5_G:string = 'https://api-harmony-teach.itheima.net/hm/userInfo'
//查询反馈类型
const HM_6_G:string = 'https://api-harmony-teach.itheima.net/hm/userInfo'
//查询打卡签到信息
const HM_7_G:string = 'https://api-harmony-teach.itheima.net/hm/userInfo'
//素材上传
const HM_8_P:string = 'https://api-harmony-teach.itheima.net/hm/userInfo'

